name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish-jsr:
    if: ${{github.repository_owner=='asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: npx jsr publish
